---
title: "P395AnalysisDraft"
author: "Jasir Rahman"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

Setup:
```{r}
##11/07/23
#General Data on Lobbying
rm(list=ls())  
#setwd
setwd("~/Desktop/R/POLI 395/POLI 395 Project")
#libraries + packages
library(devtools)
library(foreign)
library(qss)
library(ggplot2)
library(dplyr)
library(stargazer)
library(stringr)
library(tidyverse)
library(texreg)

#Load in data
og <- read.csv('original_data.csv')
blob <- read.csv('bills_lobbied_on.csv')  
lobby <- read.csv('lobbying_data_full_2020.csv')  #lobbying data
leg_116 <- read.csv('house_legislation_116.csv')  #House legislative data
mem_116 <- read.csv('house_members_116.csv')  #House member data
bills <- read.csv('bills_116.csv')  #House and Senate legislative data

```

Data cleaning:
```{r}
#join on id.poli395
blog <- blob %>% 
  full_join(og, by = c('id.poli395' = 'id.poli395'))
#restrict to the 116th congress
blog <- blog %>% 
  filter(congress == 116)

#subset data to include only necessary columns
blog = blog[, c(1:5,8,10,17,18,20,27,28,30,31,38)]
#rename H.R. in data
blog$bill_name <- gsub("H.R. ", "H.R.", blog$bill_name)

##merging bill statuses on bill names'
bills = bills[, c(3,4,5,7,8,9,10,12)]
bills$bill_number <- gsub("HB", "H.R.", bills$bill_number)
bills <- bills %>% 
  rename(bill_name = bill_number)

#rename variable name to sponsor in mems_116
mem_116 <- mem_116 %>%
  rename(sponsor = name_id)

#create list of strings from all bill names 
leg_116 = leg_116[, c(1,3,4)]

#merge data based on column sponsor for both bills
sponsor <- leg_116 %>%
  full_join(mem_116, by = c("sponsor" = "sponsor"))

#filter data by keeping inclusive to cells in bill_id with data
sponsor <- sponsor[complete.cases(sponsor$bill_id),]
sponsor <- sponsor %>% 
  rename(bill_name= bill_id)
```

merge data
```{r}
#merge data
data <- inner_join(blog, sponsor, by = "bill_name")
data <- inner_join(data, bills, by = "bill_name")
#filter out data for bills without gvp focus
```


Checking summary statistics:
```{r}
#check on summary statistics for ind. or dep. variables
summary(data$dollar_amount)
summary(data$status)
#check and print percent missing for ind. and dep. variables
missing_percent_dollar_amount <- sum(is.na(data$dollar_amount)) / length(data$dollar_amount) * 100
missing_percent_status <- sum(is.na(data$status)) / length(data$status) * 100
cat("Percentage of missing values in 'dollar_amount':", missing_percent_dollar_amount, "%\n")
cat("Percentage of missing values in 'status':", missing_percent_status, "%\n")
```

Running Lobby-Centric Analysis:

```{r}
##Create 2 binary sets of vars
#1st is for distinguishing between 1s and 2+4
data <- data%>% 
  mutate(committee = ifelse(status > 1, 1, 0))  #1 for out of committee 0 for not
#2nd is for distinguishing between 1+2 and 4s
data <- data%>% 
  mutate(passed = ifelse(status > 2, 1, 0))  #1 for passed 0 for not
##Models for Committee Outcome
#Model w/ no controls
cmodel <- lm(committee ~ dollar_amount, data = data)
summary(cmodel)
#Model w/ party + state controls
cmodel1 <- lm(committee ~ dollar_amount + current_party + state, data = data)
#summary(cmodel1)
#Model w/ sponsor controls but neither state nor party
cmodel2 <- lm(committee ~ dollar_amount + sponsor, data = data)
summary(cmodel2)
#Model w/ registrant controls
cmodel3 <- lm(committee ~ dollar_amount + registrant_id, data = data)
#summary(cmodel3)

##Models for Passage Outcome
#Model w/ no controls
pmodel <- lm(passed ~ dollar_amount, data = data)
summary(pmodel)
#Model w/ party + state controls
pmodel1 <- lm(committee ~ dollar_amount + current_party + state, data = data)
#summary(pmodel1)
#Model w/ sponsor controls but neither state nor party
pmodel2 <- lm(passed ~ dollar_amount + sponsor, data = data)
#summary(pmodel2)
#Model w/ registrant controls
pmodel3 <- lm(passed ~ dollar_amount + registrant_id, data = data)
#summary(pmodel2)
```

New Subset for Bill-Centric Analysis and Data Visualization:

```{r}
dataviz <- data
dataviz <- dataviz[!is.na(dataviz$dollar_amount), ]
dataviz <- dataviz[!duplicated(dataviz$bill_name), ]

dataviz <- data %>% 
  group_by(bill_name) %>% 
  mutate(totalspent = sum(dollar_amount))

dataviz <- dataviz[, c("bill_name", "status", "current_party", "state", "sponsor", "committee", "passed", "totalspent")]
dataviz <- dataviz[!is.na(dataviz$totalspent), ]
dataviz <- dataviz[!duplicated(dataviz$bill_name), ]
```

Bill-Centric Analysis:
```{r}
##Models for Committee Outcome
#Model w/ no controls
cm <- lm(committee ~ totalspent, data = dataviz)
summary(cm)
#Model w/ party + state controls
cm1 <- lm(committee ~ totalspent + current_party + state, data = dataviz)
#summary(cm1)
#Model w/ sponsor controls but neither state nor party
cm2 <- lm(committee ~ totalspent + sponsor, data = dataviz)
#summary(cm2)

##Models for Passage Outcome
#Model w/ no controls
pm <- lm(passed ~ totalspent, data = dataviz)
summary(pm)
#Model w/ party + state controls
pm1 <- lm(committee ~ totalspent + current_party + state, data = dataviz)
summary(pm1)
#Model w/ sponsor controls but neither state nor party
pm2 <- lm(passed ~ totalspent + sponsor, data = dataviz)
summary(pm2)
```

Output Table:
```{r}
#Latex Table
#reason we are using 'cm2' and 'pm2' for the table is that it controls for the sponsors
#controlling for sponsors can be a proxy for a few things:
#sponsor themselves, party, state, seniority, committee membership
wordreg(list(cm2, pm2), file = 'results.docx', digits = 2,
        include.rsquared = FALSE, include.adjrs = FALSE)
```

Density Plot for Passed Legislation:
```{r}
ggplot(dataviz, aes(log(totalspent), fill = factor(passed))) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Density Plot of Lobby Dollars for Bills",
    x = "Lobby Dollars (Log Transformed)",
    y = "Density",
    fill = "Passed Out \n of House?") +
  scale_fill_discrete(labels = c("Did Not Pass", "Passed"))
```

Density Plot for Committee Legislation:
```{r}
ggplot(dataviz, aes(log(totalspent), fill = factor(committee))) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Density Plot of Lobby Dollars for Bills by Status",
    x = "Lobby Dollars (Log Transformed)",
    y = "Density",
    fill = "Passed Out \n of Committee?") +
  scale_fill_discrete(labels = c("Did Not Pass", "Passed"))
```

Density Plot for Levels:
```{r}
ggplot(dataviz, aes(log(totalspent), fill = factor(status))) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Density Plot of Lobby Dollars for Bills by Status",
    x = "Lobby Dollars (Log Transformed)",
    y = "Density",
    fill = "Bill End Status") +
  scale_fill_discrete(labels = c("In Committee", "Out Committee", "Passed"))
```

